package App;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.sql.PreparedStatement;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.Locale;

public class DataBarang extends javax.swing.JFrame {

    Connection conn;

    public DataBarang() {
        initComponents();
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        connect();
        loadData("");
        svg.setIcon(new FlatSVGIcon(getClass().getResource("/Design/Barang-Fix.svg")));

        jTextField1.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                search();
            }

            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                search();
            }

            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                search();
            }

            private void search() {
                String keyword = jTextField1.getText();
                loadData(keyword);
            }
        });
    }

    // Koneksi ke database
    void connect() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/kasirkoperasismada", "root", "");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal koneksi: " + e.getMessage());
        }
    }

    void loadData(String keyword) {
        DefaultTableModel model = new DefaultTableModel(
                new String[]{"Nama Barang", "Harga", "Stok", "Barcode"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        try {
            String sql = "SELECT * FROM barang WHERE nama_barang LIKE ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, "%" + keyword + "%");
            ResultSet rs = pst.executeQuery();

            DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance(new Locale("in", "ID"));
            DecimalFormatSymbols formatRp = new DecimalFormatSymbols();
            formatRp.setCurrencySymbol("Rp. ");
            formatRp.setMonetaryDecimalSeparator(',');
            formatRp.setGroupingSeparator('.');
            kursIndonesia.setDecimalFormatSymbols(formatRp);
            kursIndonesia.setMaximumFractionDigits(0);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("Nama_Barang"),
                    kursIndonesia.format(rs.getDouble("Harga")),
                    rs.getInt("Stok"),
                    rs.getString("Barcode")
                });
            }
            TblBarang.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal load data: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TblBarang = new javax.swing.JTable();
        BtnDashboard = new javax.swing.JLabel();
        BtnLaporan = new javax.swing.JLabel();
        BtnKasir = new javax.swing.JLabel();
        BtnUser = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        BtnHapus = new javax.swing.JButton();
        BtnTambah = new javax.swing.JButton();
        svg = new javax.swing.JLabel();
        png = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NAMA BARANG", "STOK", "HARGA", "BARCODE"
            }
        ));
        jScrollPane1.setViewportView(TblBarang);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 890, 500));

        BtnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnDashboardMouseClicked(evt);
            }
        });
        getContentPane().add(BtnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 35, 192, 58));

        BtnLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnLaporanMouseClicked(evt);
            }
        });
        getContentPane().add(BtnLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 302, 192, 58));

        BtnKasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnKasirMouseClicked(evt);
            }
        });
        getContentPane().add(BtnKasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 124, 192, 58));

        BtnUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnUserMouseClicked(evt);
            }
        });
        getContentPane().add(BtnUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 391, 192, 58));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 55, 890, 66));

        BtnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnHapus.setText("Hapus");
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(BtnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 662, 185, 60));

        BtnTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnTambah.setText("Tambah");
        BtnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambahActionPerformed(evt);
            }
        });
        getContentPane().add(BtnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 662, 185, 60));
        getContentPane().add(svg, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 0, -1, -1));

        png.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Design/Barang-Fix.png"))); // NOI18N
        getContentPane().add(png, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambahActionPerformed
        TambahBarang tambah = new TambahBarang();
        tambah.setVisible(true);
        tambah.pack();
        tambah.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_BtnTambahActionPerformed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        try {
            Connection connection = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/kasirkoperasismada", "root", "");

            int selecrow = TblBarang.getSelectedRow();
            if (selecrow == -1) {
                JOptionPane.showMessageDialog(this, "Silahkan pilih baris yang ingin dihapus");
                return;
            }

            int confirm = JOptionPane.showConfirmDialog(this, "Apakah yakin ingin menghapus baris ini!",
                    "Konfirmasi", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {

                String NamaBarang = TblBarang.getValueAt(selecrow, 0).toString().trim();

                System.out.println("Nama Barang yang akan dihapus: " + NamaBarang);

                PreparedStatement delete = connection.prepareStatement("DELETE FROM barang WHERE Nama_Barang = ?");
                delete.setString(1, NamaBarang);
                int rowdelete = delete.executeUpdate();

                if (rowdelete > 0) {
                    DefaultTableModel model = (DefaultTableModel) TblBarang.getModel();
                    model.removeRow(selecrow);
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
                } else {
                    JOptionPane.showMessageDialog(this, "Data tidak ditemukan!");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
        }
    }//GEN-LAST:event_BtnHapusActionPerformed

    private void BtnDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnDashboardMouseClicked
        Dashboard d = new Dashboard();
        d.setVisible(true);
        d.pack();
        d.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_BtnDashboardMouseClicked

    private void BtnKasirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnKasirMouseClicked
        Kasir d = new Kasir();
        d.setVisible(true);
        d.pack();
        d.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_BtnKasirMouseClicked

    private void BtnLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLaporanMouseClicked
        Laporan d = new Laporan();
        d.setVisible(true);
        d.pack();
        d.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_BtnLaporanMouseClicked

    private void BtnUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnUserMouseClicked
        User d = new User();
        d.setVisible(true);
        d.pack();
        d.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_BtnUserMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnDashboard;
    private javax.swing.JButton BtnHapus;
    private javax.swing.JLabel BtnKasir;
    private javax.swing.JLabel BtnLaporan;
    private javax.swing.JButton BtnTambah;
    private javax.swing.JLabel BtnUser;
    private javax.swing.JTable TblBarang;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel png;
    private javax.swing.JLabel svg;
    // End of variables declaration//GEN-END:variables
}
